// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgtxBuZn3GMGR9u9fKwz0q5twsTM7cChs',
    appId: '1:93212847057:web:f544aeb1417f0bc6a24ef0',
    messagingSenderId: '93212847057',
    projectId: 'classichat-24ddc',
    authDomain: 'classichat-24ddc.firebaseapp.com',
    storageBucket: 'classichat-24ddc.appspot.com',
    measurementId: 'G-0VE9KTL0G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeab_XjkUd_lI9ups2SZiDok1drCrKuO8',
    appId: '1:93212847057:android:23244e73d621d33ea24ef0',
    messagingSenderId: '93212847057',
    projectId: 'classichat-24ddc',
    storageBucket: 'classichat-24ddc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzKqr5Htkppc_Rf-DHVuEOP7bE5T4UU-o',
    appId: '1:93212847057:ios:b17a4dbc4ad1edf2a24ef0',
    messagingSenderId: '93212847057',
    projectId: 'classichat-24ddc',
    storageBucket: 'classichat-24ddc.appspot.com',
    iosClientId: '93212847057-92grmunm2q21gi4ds5eb385fmeva3mqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.classiChat',
  );
}
